apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-querier
spec:
    replicas: 0
    selector:
        matchLabels:
            app: greeting-querier
    template:
        metadata:
            labels:
                app: greeting-querier
        spec:
            containers:
                -   name: greeting-querier
                    image: arnecdn/greeting-querier:0.2
                    imagePullPolicy: Never
                    resources:
                        requests:
                            memory: "8Mi"
                            cpu: "200m"
                        limits:
                            cpu: "500m"
                            memory: "16Mi"
                    ports:
                        -   containerPort: 8080
                    env:
                        - name: APP__DB__DATABASE_URL
                          value: "postgres://greeting_rust:Z3JlZXRpbmdfcnVzdAo=@postgres-greeting:5432/greeting_rust"
                        - name: APP__OTEL_COLLECTOR__OLTP_ENDPOINT
                          value: "http://grafana-alloy:4317"
                        - name: APP__KUBE__MY_POD_NAME
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.name

                    command:
                              - "/usr/bin/server"


---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: greeting-querier-cpu-scaledobject
    namespace: default
spec:
    scaleTargetRef:
        name: greeting-querier
    pollingInterval: 10
    cooldownPeriod: 10                               # Optional. Default: 300 seconds
    minReplicaCount: 1
    maxReplicaCount: 10  # Max can go upto num of partitions you have in the topic
    triggers:
        - type: cpu
          metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          metadata:
              value: "500"